### ISSUE TITLE
BattleTechModLoaderInjector exception error - 0.64 release

### ISSUE THREAD

**Issue by silvercheckmate** [janxious/BattleTechModLoader#16]
This is the error output when the injector is run via command line.
This is the `0.64` release and injecting into battletech flashpoint.

```ERROR: An exception occured: System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem.Primitives, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.IO.FileSystem.Primitives, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at BattleTechModLoader.BTMLInjector.IsInjected(String dllPath, Boolean& isCurrentInjection, String& gameVersion)

   at BattleTechModLoader.BTMLInjector.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)
to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].```

**Comment by silvercheckmate** [comment]
For what its worth, I saw #15 and also added `mono.cecil.dll` to the `managed` folder, but still resulted in the same error

**Comment by janxious** [comment]
Try using the 0.7.0 release. Adding Mono.Cecil.dll to v0.6.4 will not have any effect.

**Comment by silvercheckmate** [comment]
Cool `0.7.0` is working for me, thanks for making this mod loader for us :)
